<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Ecommerce Regression " duration-ms="1131" started-at="2021-06-16T13:17:35Z" finished-at="2021-06-16T13:17:36Z">
    <groups>
    </groups>
    <test name="Add to cart Module" duration-ms="1131" started-at="2021-06-16T13:17:35Z" finished-at="2021-06-16T13:17:36Z">
      <class name="com.test.ecommerce.AddtoCart">
        <test-method status="PASS" signature="readdata()[pri:0, instance:com.test.ecommerce.AddtoCart@340f438e]" name="readdata" is-config="true" duration-ms="17" started-at="2021-06-16T18:47:33Z" finished-at="2021-06-16T18:47:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readdata -->
        <test-method status="PASS" signature="driversetup()[pri:0, instance:com.test.ecommerce.AddtoCart@340f438e]" name="driversetup" is-config="true" duration-ms="1979" started-at="2021-06-16T18:47:33Z" depends-on-methods="com.test.dataUtilities.Readfromproperty.readdata" finished-at="2021-06-16T18:47:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driversetup -->
        <test-method status="FAIL" signature="addtocart_fromsearchresults()[pri:0, instance:com.test.ecommerce.AddtoCart@340f438e]" name="addtocart_fromsearchresults" duration-ms="26" started-at="2021-06-16T18:47:35Z" finished-at="2021-06-16T18:47:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.ecommerce.AddtoCart.addtocart_fromsearchresults(AddtoCart.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addtocart_fromsearchresults -->
        <test-method status="FAIL" signature="addtocart_pricevalidation()[pri:0, instance:com.test.ecommerce.AddtoCart@340f438e]" name="addtocart_pricevalidation" duration-ms="879" started-at="2021-06-16T18:47:35Z" finished-at="2021-06-16T18:47:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	failed - price is not matched expected [90] but found [95]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	failed - price is not matched expected [90] but found [95]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.test.ecommerce.AddtoCart.addtocart_pricevalidation(AddtoCart.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addtocart_pricevalidation -->
        <test-method status="PASS" signature="closedriver()[pri:0, instance:com.test.ecommerce.AddtoCart@340f438e]" name="closedriver" is-config="true" duration-ms="179" started-at="2021-06-16T18:47:36Z" finished-at="2021-06-16T18:47:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedriver -->
      </class> <!-- com.test.ecommerce.AddtoCart -->
    </test> <!-- Add to cart Module -->
  </suite> <!-- Ecommerce Regression  -->
</testng-results>
