<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LR7VCPRQ" name="ecommerce.AddtoWishList" tests="6" failures="0" timestamp="5 Jun 2021 07:39:46 GMT" time="0.015" errors="1">
  <testcase name="login" time="0.001" classname="ecommerce.AddtoWishList"/>
  <testcase name="login" time="0.001" classname="ecommerce.AddtoWishList"/>
  <testcase name="list_additems" time="0.007" classname="ecommerce.AddtoWishList">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: list_additems([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)list1,(java.lang.String)product1,(java.lang.String)www.amazon.com]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: list_additems([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)list1,(java.lang.String)product1,(java.lang.String)www.amazon.com]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1228)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1125)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- list_additems -->
  <testcase name="list_removeitems" time="0.004" classname="ecommerce.AddtoWishList"/>
  <testcase name="login" time="0.001" classname="ecommerce.AddtoWishList"/>
  <testcase name="lockuser" time="0.001" classname="ecommerce.AddtoWishList"/>
</testsuite> <!-- ecommerce.AddtoWishList -->
